updating to what the output recommended when running build-pipeline
ERROR: No artifacts found that match the file pattern "build/libs/**/*.jar". Configuration error?
Finished: FAILURE